[book]
authors = ["drpaneas"]
language = "en"
src = "docs"
title = "GoSprite64 Documentation"
description = "Technical reference for the GoSprite64 library to help you make 2D games for Nintendo64."

[build]
build-dir = "book"

[output.html]
cname="gosprite64.dev"
