[book]
authors = ["drpaneas"]
language = "en"
src = "docs"
title = "GoSprite64 Documentation"
description = "Beginner-first documentation for building 2D Nintendo 64 games with GoSprite64."

[build]
build-dir = "book"

[output.html]
cname="gosprite64.dev"
