//go:build !noos

// Command audiogen generates an audio_embed.go file with embedded audio files for gosprite64.
// This is a host-only tool that runs on your development machine, not on the N64.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	// Parse command line flags
	var outputDir string
	var v1Mode bool
	var romBudgetFlag int
	var sfxBudgetFlag int
	var devRawFlag bool
	var packageFlag string
	flag.StringVar(&outputDir, "dir", ".", "Directory where the audio_embed.go file will be created")
	flag.BoolVar(&verbose, "verbose", false, "Enable verbose output")
	flag.BoolVar(&v1Mode, "v1", false, "Enable V1 audio pipeline (VADPCM)")
	flag.IntVar(&romBudgetFlag, "rom-budget", DefaultROMBudget, "ROM budget for all audio data in bytes")
	flag.IntVar(&sfxBudgetFlag, "sfx-resident-budget", DefaultSFXResidentCap, "SFX resident budget in bytes")
	flag.BoolVar(&devRawFlag, "dev-raw", false, "Emit uncompressed PCM (deferred, not implemented in V1)")
	flag.StringVar(&packageFlag, "package", "", "Override package name for generated files")
	flag.Parse()

	if v1Mode {
		if devRawFlag {
			fmt.Println("-dev-raw is not implemented in V1. Remove the flag or wait for V2.")
			os.Exit(1)
		}
		if err := runV1Pipeline(outputDir, packageFlag, romBudgetFlag, sfxBudgetFlag); err != nil {
			fmt.Printf("V1 pipeline error: %v\n", err)
			os.Exit(1)
		}
		return
	}

	// Prepare all runtime audio files, preferring WAV sources when present.
	audioFiles, err := prepareAudioFiles(outputDir)
	if err != nil {
		fmt.Printf("Error preparing audio files: %v\n", err)
		os.Exit(1)
	}

	// Filter out invalid audio files and convert to relative paths
	var audioRelPaths []string
	for _, file := range audioFiles {
		relPath, err := filepath.Rel(outputDir, file)
		if err != nil {
			fmt.Printf("Error getting relative path for %s: %v\n", file, err)
			continue
		}
		if verbose {
			fmt.Printf("Including audio file: %s\n", relPath)
		}
		audioRelPaths = append(audioRelPaths, relPath)
	}

	// If no audio files were found, exit
	if len(audioRelPaths) == 0 {
		fmt.Printf("No audio files (*.raw) found in %s\n", outputDir)

		// Check if an audio_embed.go file exists and remove it if it does
		embedGoPath := filepath.Join(outputDir, "audio_embed.go")
		if fileExists(embedGoPath) {
			err := os.Remove(embedGoPath)
			if err != nil {
				fmt.Printf("Warning: Failed to remove existing audio_embed.go file: %v\n", err)
			} else if verbose {
				fmt.Printf("Removed existing audio_embed.go file as no audio files were found\n")
			}
		}
		return
	}

	// Generate the embed.go file
	err = generateEmbedFile(outputDir, audioFiles)
	if err != nil {
		fmt.Printf("Error generating audio_embed.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated audio_embed.go with %d audio files\n", len(audioRelPaths))
}

// generateEmbedFile creates the audio_embed.go file with the embedded audio files
func generateEmbedFile(dir string, audioFiles []string) error {
	if len(audioFiles) == 0 {
		return nil
	}

	audioRelPaths := make([]string, 0, len(audioFiles))
	for _, file := range audioFiles {
		relPath, err := filepath.Rel(dir, file)
		if err != nil {
			return fmt.Errorf("failed to resolve relative audio path for %s: %w", file, err)
		}
		audioRelPaths = append(audioRelPaths, relPath)
	}

	// Create the output file
	outputFile := filepath.Join(dir, "audio_embed.go")
	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer func() {
		closeErr := f.Close()
		if closeErr != nil && err == nil {
			err = closeErr
		}
	}()

	// Get the package name from the current directory
	pkgName := "main"
	if dir != "." {
		pkgName = filepath.Base(dir)
	}

	// Generate the file content
	content := fmt.Sprintf(`// Code generated by audiogen; DO NOT EDIT.

package %s

import (
	"embed"

	"github.com/drpaneas/gosprite64"
)

//go:embed %s
var audioFS embed.FS

func init() {
	// Initialize the audio filesystem with embedded audio files
	gosprite64.SetAudioFS(audioFS)
}
`, pkgName, strings.Join(audioRelPaths, " "))

	// Write the content to the file
	_, err = f.WriteString(content)
	if err != nil {
		return fmt.Errorf("failed to write to output file: %w", err)
	}

	if verbose {
		fmt.Printf("Generated %s with %d audio files\n", outputFile, len(audioFiles))
	}
	return nil
}

// fileExists checks if a file exists and is not a directory
func fileExists(filename string) bool {
	info, err := os.Stat(filename)
	return err == nil && !info.IsDir()
}

// Global variable for verbose output
var verbose bool

func runV1Pipeline(dir, packageName string, romBudget, sfxBudget int) error {
	sfxSources, musicSources, err := scanAudioDirV1(dir)
	if err != nil {
		return err
	}
	if len(sfxSources) == 0 && len(musicSources) == 0 {
		fmt.Println("No audio assets found in assets/audio/")
		return nil
	}

	buildDir := filepath.Join(dir, BuildDirName)
	if err := os.MkdirAll(buildDir, 0o755); err != nil {
		return err
	}

	var allData []byte
	var allAux []byte
	var manifest []manifestInput
	var sfxID uint16
	var musicID uint16

	for _, src := range sfxSources {
		result, err := encodeAsset(src)
		if err != nil {
			return fmt.Errorf("encode sfx %s: %w", src.Name, err)
		}
		if err := validateLoopInvariants(result.LoopStart, result.LoopLen, result.EncodedFrames, result.Loop); err != nil {
			return fmt.Errorf("sfx %s: %w", src.Name, err)
		}
		manifest = append(manifest, manifestInput{
			Name: src.Name, Class: "sfx", ID: sfxID, Rate: src.Rate,
			AudibleFrames: result.AudibleFrames, EncodedFrames: result.EncodedFrames,
			DataOffset: uint32(len(allData)), DataBytes: uint32(len(result.CompressedData)),
			AuxOffset: uint32(len(allAux)), AuxBytes: uint32(len(result.CodebookBytes)),
		})
		allData = append(allData, result.CompressedData...)
		allAux = append(allAux, result.CodebookBytes...)
		sfxID++
	}

	for _, src := range musicSources {
		result, err := encodeAsset(src)
		if err != nil {
			return fmt.Errorf("encode music %s: %w", src.Name, err)
		}
		if err := validateLoopInvariants(result.LoopStart, result.LoopLen, result.EncodedFrames, result.Loop); err != nil {
			return fmt.Errorf("music %s: %w", src.Name, err)
		}
		loopState := captureStateAt(&result.Codebook, result.CompressedData, int(result.LoopStart))
		loopStateBytes := stateToBytes(loopState)
		manifest = append(manifest, manifestInput{
			Name: src.Name, Class: "music", ID: musicID, Rate: src.Rate,
			AudibleFrames: result.AudibleFrames, EncodedFrames: result.EncodedFrames,
			DataOffset: uint32(len(allData)), DataBytes: uint32(len(result.CompressedData)),
			AuxOffset: uint32(len(allAux)), AuxBytes: uint32(len(result.CodebookBytes) + len(loopStateBytes)),
			Loop: true, LoopStart: result.LoopStart, LoopLen: result.LoopLen,
		})
		allData = append(allData, result.CompressedData...)
		allAux = append(allAux, result.CodebookBytes...)
		allAux = append(allAux, loopStateBytes...)
		musicID++
	}

	if err := os.WriteFile(filepath.Join(buildDir, AudioBlobName), allData, 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(buildDir, AudioAuxName), allAux, 0o644); err != nil {
		return err
	}
	if err := generateManifestAndConsts(dir, manifest, packageName); err != nil {
		return err
	}
	return computeAndWriteBudget(dir, manifest, romBudget, sfxBudget)
}
