//go:build !noos

package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/drpaneas/gosprite64/internal/audiov1"
)

type AudioSource struct {
	Name  string
	Path  string
	Class audiov1.AssetClass
	Rate  int
}

func scanAudioDirV1(dir string) (sfx, music []AudioSource, err error) {
	sfx, err = scanWAVDir(filepath.Join(dir, "assets", "audio", "sfx"), audiov1.ClassSFX, DefaultSFXRate)
	if err != nil {
		return nil, nil, err
	}
	music, err = scanWAVDir(filepath.Join(dir, "assets", "audio", "music"), audiov1.ClassMusic, DefaultMusicRate)
	if err != nil {
		return nil, nil, err
	}
	return sfx, music, nil
}

func scanWAVDir(dir string, class audiov1.AssetClass, rate int) ([]AudioSource, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}

	var sources []AudioSource
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".wav") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".wav")
		sources = append(sources, AudioSource{Name: name, Path: filepath.Join(dir, e.Name()), Class: class, Rate: rate})
	}
	slices.SortFunc(sources, func(a, b AudioSource) int {
		return strings.Compare(a.Name, b.Name)
	})
	return sources, nil
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

type EncodedResult struct {
	AudibleFrames  uint32
	EncodedFrames  uint32
	CompressedData []byte
	Codebook       audiov1.Codebook
	CodebookBytes  []byte
	Loop           bool
	LoopStart      uint32
	LoopLen        uint32
}

func encodeAsset(src AudioSource) (EncodedResult, error) {
	f, err := os.Open(src.Path)
	if err != nil {
		return EncodedResult{}, fmt.Errorf("open %s: %w", src.Path, err)
	}
	defer f.Close()

	mono, sourceSampleRate, err := readWAVMono(f)
	if err != nil {
		return EncodedResult{}, fmt.Errorf("read wav %s: %w", src.Path, err)
	}
	mono = resampleMono(mono, sourceSampleRate, src.Rate)

	audibleFrames := uint32(len(mono))
	padded := padToBlockBoundary(mono)
	encoded := EncodeVADPCM(padded)

	return EncodedResult{
		AudibleFrames:  audibleFrames,
		EncodedFrames:  uint32(len(padded)),
		CompressedData: encoded.Data,
		Codebook:       encoded.Codebook,
		CodebookBytes:  codebookToBytes(encoded.Codebook),
		Loop:           src.Class == audiov1.ClassMusic,
		LoopStart:      0,
		LoopLen:        uint32(len(padded)),
	}, nil
}

func padToBlockBoundary(samples []int16) []int16 {
	rem := len(samples) % audiov1.BlockSamples
	if rem == 0 {
		return samples
	}
	padded := make([]int16, len(samples)+audiov1.BlockSamples-rem)
	copy(padded, samples)
	return padded
}

func codebookToBytes(cb audiov1.Codebook) []byte {
	buf := make([]byte, audiov1.CodebookInts*2)
	idx := 0
	for p := 0; p < audiov1.PredictorCount; p++ {
		for o := 0; o < audiov1.Order; o++ {
			for s := 0; s < audiov1.StateLen; s++ {
				v := cb[p][o][s]
				buf[idx] = byte(v >> 8)
				buf[idx+1] = byte(v)
				idx += 2
			}
		}
	}
	return buf
}

func stateToBytes(s audiov1.State) []byte {
	buf := make([]byte, audiov1.StateLen*2)
	for i := 0; i < audiov1.StateLen; i++ {
		buf[i*2] = byte(s[i] >> 8)
		buf[i*2+1] = byte(s[i])
	}
	return buf
}

type manifestInput struct {
	Name          string
	Class         string
	ID            uint16
	Rate          int
	AudibleFrames uint32
	EncodedFrames uint32
	DataOffset    uint32
	DataBytes     uint32
	AuxOffset     uint32
	AuxBytes      uint32
	Loop          bool
	LoopStart     uint32
	LoopLen       uint32
}

func generateManifestAndConsts(dir string, inputs []manifestInput, pkgOverride string) error {
	if err := generateConstPackage(dir, "sfx", inputs); err != nil {
		return err
	}
	if err := generateConstPackage(dir, "music", inputs); err != nil {
		return err
	}
	return generateEmbedFileV1(dir, inputs, pkgOverride)
}

func generateConstPackage(dir, class string, inputs []manifestInput) error {
	hasEntries := false
	for _, in := range inputs {
		if in.Class == class {
			hasEntries = true
			break
		}
	}
	if !hasEntries {
		return nil
	}

	pkgDir := filepath.Join(dir, class)
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		return err
	}

	libPkg := "github.com/drpaneas/gosprite64/audio/" + class
	var b strings.Builder
	b.WriteString("// Code generated by audiogen; DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", class))
	b.WriteString(fmt.Sprintf("import audio%s %q\n\n", class, libPkg))
	b.WriteString(fmt.Sprintf("type ID = audio%s.ID\n\n", class))
	b.WriteString("const (\n")
	for _, in := range inputs {
		if in.Class == class {
			b.WriteString(fmt.Sprintf("\t%s ID = %d\n", snakeToPascal(in.Name), in.ID))
		}
	}
	b.WriteString(")\n")
	return os.WriteFile(filepath.Join(pkgDir, "ids.go"), []byte(b.String()), 0o644)
}

func detectPackageName(dir string) string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "main"
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || e.Name() == AudioEmbedName {
			continue
		}
		if pkg := readPackageClause(filepath.Join(dir, e.Name())); pkg != "" {
			return pkg
		}
	}
	return "main"
}

func readPackageClause(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "package ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "package"))
		}
	}
	return ""
}

// generateEmbedFileV1 produces a single init() that registers a complete
// audio bundle, so init ordering is deterministic regardless of file naming.
func generateEmbedFileV1(dir string, inputs []manifestInput, pkgOverride string) error {
	pkgName := pkgOverride
	if pkgName == "" {
		pkgName = detectPackageName(dir)
	}

	var b strings.Builder
	b.WriteString("// Code generated by audiogen; DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", pkgName))
	b.WriteString("import (\n")
	b.WriteString("\t_ \"embed\"\n\n")
	b.WriteString("\t\"github.com/drpaneas/gosprite64\"\n")
	b.WriteString(")\n\n")
	b.WriteString(fmt.Sprintf("//go:embed %s/%s\n", BuildDirName, AudioBlobName))
	b.WriteString("var audioV1Data []byte\n\n")
	b.WriteString(fmt.Sprintf("//go:embed %s/%s\n", BuildDirName, AudioAuxName))
	b.WriteString("var audioV1Aux []byte\n\n")
	b.WriteString("var audioBundle = gosprite64.AudioBundle{\n")
	b.WriteString("\tAssets: []gosprite64.AudioAsset{\n")

	for _, in := range inputs {
		classVal := 0
		flags := 0
		maxInst := DefaultMaxSFXInstances
		if in.Class == "sfx" {
			flags |= int(audiov1.FlagResident)
		} else {
			classVal = 1
			flags |= int(audiov1.FlagStreamed)
			maxInst = DefaultMaxMusicInstances
		}
		if in.Loop {
			flags |= int(audiov1.FlagLoop)
		}
		b.WriteString(fmt.Sprintf("\t\t{ID: %d, Class: %d, Flags: %d, Rate: %d, "+
			"AudibleFrames: %d, EncodedFrames: %d, LoopStart: %d, LoopLen: %d, "+
			"DataOffset: %d, DataBytes: %d, AuxOffset: %d, AuxBytes: %d, MaxInstances: %d},\n",
			in.ID, classVal, flags, in.Rate, in.AudibleFrames, in.EncodedFrames, in.LoopStart, in.LoopLen,
			in.DataOffset, in.DataBytes, in.AuxOffset, in.AuxBytes, maxInst))
	}

	b.WriteString("\t},\n")
	b.WriteString("\tData: audioV1Data,\n")
	b.WriteString("\tAux:  audioV1Aux,\n")
	b.WriteString("\tResolveSoundEffectName: func(name string) (uint16, bool) {\n")
	b.WriteString("\t\tswitch name {\n")
	for _, in := range inputs {
		if in.Class != "sfx" {
			continue
		}
		b.WriteString(fmt.Sprintf("\t\tcase %q:\n", in.Name))
		b.WriteString(fmt.Sprintf("\t\t\treturn %d, true\n", in.ID))
	}
	b.WriteString("\t\tdefault:\n")
	b.WriteString("\t\t\treturn 0, false\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t},\n")
	b.WriteString("}\n\n")

	b.WriteString("func init() {\n")
	b.WriteString("\tgosprite64.RegisterAudioBundle(audioBundle)\n")
	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, AudioEmbedName), []byte(b.String()), 0o644)
}

func validateLoopInvariants(loopStart, loopLen, totalFrames uint32, hasLoop bool) error {
	if !hasLoop {
		return nil
	}
	if loopStart%audiov1.BlockSamples != 0 {
		return fmt.Errorf("LoopStartFrame %d is not aligned to %d", loopStart, audiov1.BlockSamples)
	}
	if loopLen%audiov1.BlockSamples != 0 {
		return fmt.Errorf("LoopLengthFrames %d is not aligned to %d", loopLen, audiov1.BlockSamples)
	}
	if loopStart+loopLen > totalFrames {
		return fmt.Errorf("loop range [%d, %d) exceeds total frames %d", loopStart, loopStart+loopLen, totalFrames)
	}
	return nil
}
