// Code generated by audiogen; DO NOT EDIT.

package main

import (
	"embed"

	"github.com/drpaneas/gosprite64"
)

//go:embed sfx_paddle_computer.raw sfx_paddle_player.raw sfx_score_computer.raw sfx_score_player.raw sfx_start.raw sfx_wall.raw
var audioFS embed.FS

func init() {
	// Initialize the audio filesystem with embedded audio files
	gosprite64.SetAudioFS(audioFS)
}
