// Code generated by audiogen; DO NOT EDIT.

package main

import (
	"embed"

	"github.com/drpaneas/gosprite64"
)

//go:embed music0.raw music1.raw music2.raw music3.raw music4.raw music5.raw music6.raw
var audioFS embed.FS

func init() {
	// Initialize the audio filesystem with embedded audio files
	gosprite64.SetAudioFS(audioFS)
}
