// Code generated by audiogen; DO NOT EDIT.

package sfx

import audiosfx "github.com/drpaneas/gosprite64/audio/sfx"

type ID = audiosfx.ID

const (
	PaddleComputer ID = 0
	PaddlePlayer ID = 1
	ScoreComputer ID = 2
	ScorePlayer ID = 3
	Start ID = 4
	Wall ID = 5
)
