name: Mage CI

on:
  push:
  pull_request:

jobs:
  mage:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      # --- macOS ARM64: Install mage via Homebrew then run manually ---
      - name: Install mage using Homebrew (macOS ARM64) and run 
        if: runner.os == 'macos' && runner.arch == 'arm64'
        run: |
          brew update
          brew install mage
          mage Setup Test

      # --- Other platforms: Use mage-action ---
      - name: Run Mage Setup and Test targets with mage-action
        if: runner.os != 'macos'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: Setup Test

