name: Mage CI

on:
  push:
  pull_request:

jobs:
  mage:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      # For macOS Arm64, install mage using Homebrew.
      - name: Install mage using Homebrew (macOS ARM64)
        if: runner.os == 'macOS' && runner.arch == 'arm64'
        run: |
          brew update
          brew install mage

      # For non-macOS-ARM64 runners, use the mage-action.
      - name: Run Mage Setup and Test targets with mage-action
        if: runner.os != 'macOS' || runner.arch != 'arm64'
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: Setup Test

      # For macOS ARM64, run mage manually.
      - name: Run mage targets manually (macOS ARM64)
        if: runner.os == 'macOS' && runner.arch == 'arm64'
        run: mage Setup Test

