name: CI

on:
  push:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  mage:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      # Force a POSIX shell so direnv hook detection works
      SHELL: /bin/bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      # On Linux/macOS, install direnv & load the hook
      - name: Install & hook direnv
        if: runner.os != 'Windows'
        run: |
          # install direnv if missing
          if ! command -v direnv >/dev/null; then
            if command -v apt-get >/dev/null; then
              sudo apt-get update && sudo apt-get install -y direnv
            elif command -v brew >/dev/null; then
              brew install direnv
            else
              echo "Please install direnv on $(uname)"
              exit 1
            fi
          fi

          # Inject direnv into this shell and allow the .envrc
          eval "$(direnv hook bash)"
          direnv allow

      # Now run your mage targets in one step
      - name: mage Setup & Test
        uses: magefile/mage-action@v3
        with:
          version: latest
          # run both Setup and Test
          args: Setup Test

      # (optional) if you still need your build_examples.sh for some reason:
      - name: Run build_examples.sh
        if: runner.os != 'macOS'
        run: |
          chmod +x ./build_examples.sh
          ./build_examples.sh
